version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: casinodbdocker
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # Esto ejecuta tu script SQL automáticamente al iniciar
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persistencia para que no se borren los datos al apagar Docker
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
